### ISSUE TITLE
Obj-c

### ISSUE THREAD

**Issue by ecaste** [joehour/NotificationBanner#1]
Hello,
thank you for this usefull library but I've actually an app written in obj-c, is there a way to makes it running with your library ? It seems that the class NotificationBannerView is found, but not way to use NotificationBanner directly with methods showBanner...etc

Thank you

**Comment by joehour** [comment]
Hi,
First, you must know how to import swift code to obj-c project.
I think this [Stackoverflow thread ](http://stackoverflow.com/questions/24102104/how-to-import-swift-code-to-objective-c)can help you~
Additionally, you can refer to my [objExample project](https://github.com/joehour/NotificationBanner/tree/master/objcExample) to know how NotificationBanner library run in obj-c.

**Comment by ecaste** [comment]
Thank you for having put obj-c code sample.
